# Generated by Django 5.2.7 on 2025-10-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('is_manager', models.BooleanField(default=False)),
                ('vaction_days_left', models.PositiveIntegerField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.team')),
            ],
        ),
    ]
