# Generated by Django 5.2.7 on 2025-10-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.team'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Shift Date')),
                ('shift_type', models.CharField(choices=[('M', 'Morning'), ('N', 'Night')], max_length=1)),
                ('employees', models.ManyToManyField(blank=True, related_name='shifts', to='main_app.employee')),
            ],
        ),
    ]
