# Generated by Django 5.2.7 on 2025-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_employee_last_login_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Denied'), ('A', 'Accepted')], default='P', max_length=1),
        ),
    ]
