# Generated by Django 5.2.7 on 2025-11-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('M', 'Morning'), ('N', 'Night')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('D', 'Denied'), ('P', 'Pending'), ('A', 'Accepted')], default='P', max_length=1),
        ),
    ]
