# Generated by Django 5.2.7 on 2025-11-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_employee_groups_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vaction_days_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Denied'), ('A', 'Accepted')], default='P', max_length=1),
        ),
    ]
